// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: album.sql

package queries

import (
	"context"
)

const createAlbum = `-- name: CreateAlbum :exec
INSERT INTO album (id, title, total_discs, total_tracks)
VALUES ($1, $2, $3, $4)
ON CONFLICT (id) DO UPDATE SET
    title = EXCLUDED.title,
    total_discs = EXCLUDED.total_discs,
    total_tracks = EXCLUDED.total_tracks
`

type CreateAlbumParams struct {
	ID          string
	Title       string
	TotalDiscs  int32
	TotalTracks int32
}

func (q *Queries) CreateAlbum(ctx context.Context, arg CreateAlbumParams) error {
	_, err := q.db.Exec(ctx, createAlbum,
		arg.ID,
		arg.Title,
		arg.TotalDiscs,
		arg.TotalTracks,
	)
	return err
}

const getAlbumArtists = `-- name: GetAlbumArtists :many
SELECT album_id, artist_id, id, title FROM album_artist
JOIN artist ON artist.id = album_artist.artist_id
WHERE album_artist.album_id = $1
`

type GetAlbumArtistsRow struct {
	AlbumID  string
	ArtistID string
	ID       string
	Title    string
}

func (q *Queries) GetAlbumArtists(ctx context.Context, albumID string) ([]GetAlbumArtistsRow, error) {
	rows, err := q.db.Query(ctx, getAlbumArtists, albumID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAlbumArtistsRow
	for rows.Next() {
		var i GetAlbumArtistsRow
		if err := rows.Scan(
			&i.AlbumID,
			&i.ArtistID,
			&i.ID,
			&i.Title,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAlbumByHash = `-- name: GetAlbumByHash :one
SELECT id, title, total_discs, total_tracks FROM album
WHERE album.id = $1
LIMIT 1
`

func (q *Queries) GetAlbumByHash(ctx context.Context, id string) (Album, error) {
	row := q.db.QueryRow(ctx, getAlbumByHash, id)
	var i Album
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.TotalDiscs,
		&i.TotalTracks,
	)
	return i, err
}

const getAlbums = `-- name: GetAlbums :many
SELECT id, title, total_discs, total_tracks FROM album
`

func (q *Queries) GetAlbums(ctx context.Context) ([]Album, error) {
	rows, err := q.db.Query(ctx, getAlbums)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Album
	for rows.Next() {
		var i Album
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.TotalDiscs,
			&i.TotalTracks,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAlbumArtist = `-- name: MarkAlbumArtist :exec
INSERT INTO album_artist (album_id, artist_id)
VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type MarkAlbumArtistParams struct {
	AlbumID  string
	ArtistID string
}

func (q *Queries) MarkAlbumArtist(ctx context.Context, arg MarkAlbumArtistParams) error {
	_, err := q.db.Exec(ctx, markAlbumArtist, arg.AlbumID, arg.ArtistID)
	return err
}
