// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: artist.sql

package queries

import (
	"context"
)

const createArtist = `-- name: CreateArtist :exec
INSERT INTO artist (id, title)
VALUES ($1, $2) ON CONFLICT (id) DO NOTHING
`

type CreateArtistParams struct {
	ID    string
	Title string
}

func (q *Queries) CreateArtist(ctx context.Context, arg CreateArtistParams) error {
	_, err := q.db.Exec(ctx, createArtist, arg.ID, arg.Title)
	return err
}

const getArtistByHash = `-- name: GetArtistByHash :one
SELECT id, title FROM artist
WHERE artist.id = $1
LIMIT 1
`

func (q *Queries) GetArtistByHash(ctx context.Context, id string) (Artist, error) {
	row := q.db.QueryRow(ctx, getArtistByHash, id)
	var i Artist
	err := row.Scan(&i.ID, &i.Title)
	return i, err
}

const getArtists = `-- name: GetArtists :many
SELECT id, title FROM artist
`

func (q *Queries) GetArtists(ctx context.Context) ([]Artist, error) {
	rows, err := q.db.Query(ctx, getArtists)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Artist
	for rows.Next() {
		var i Artist
		if err := rows.Scan(&i.ID, &i.Title); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
