// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package queries

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Album struct {
	ID          string
	Title       string
	TotalDiscs  int32
	TotalTracks int32
}

type AlbumArtist struct {
	AlbumID  string
	ArtistID string
}

type AppUser struct {
	ID           string
	Username     string
	CreatedAt    pgtype.Timestamptz
	LastLogin    pgtype.Timestamptz
	PasswordEnc  []byte
	PasswordHash string
}

type Artist struct {
	ID    string
	Title string
}

type Track struct {
	ID          string
	Title       string
	AlbumID     pgtype.Text
	DiscNumber  int32
	TrackNumber int32
	Year        int32
	Genre       string
	Composer    string
	FilePath    string
	FileHash    string
}

type TrackArtist struct {
	TrackID  string
	ArtistID string
}
