// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: track.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTrack = `-- name: CreateTrack :exec
INSERT INTO track
    (
        id,
        title,
        album_id,
        disc_number,
        track_number,
        year,
        genre,
        composer,
        file_path,
        file_hash
    )
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
ON CONFLICT (id) DO UPDATE SET
    title = EXCLUDED.title,
    album_id = EXCLUDED.album_id,
    disc_number = EXCLUDED.disc_number,
    track_number = EXCLUDED.track_number,
    year = EXCLUDED.year,
    genre = EXCLUDED.genre,
    composer = EXCLUDED.composer,
    file_path = EXCLUDED.file_path,
    file_hash = EXCLUDED.file_hash
`

type CreateTrackParams struct {
	ID          string
	Title       string
	AlbumID     pgtype.Text
	DiscNumber  int32
	TrackNumber int32
	Year        int32
	Genre       string
	Composer    string
	FilePath    string
	FileHash    string
}

func (q *Queries) CreateTrack(ctx context.Context, arg CreateTrackParams) error {
	_, err := q.db.Exec(ctx, createTrack,
		arg.ID,
		arg.Title,
		arg.AlbumID,
		arg.DiscNumber,
		arg.TrackNumber,
		arg.Year,
		arg.Genre,
		arg.Composer,
		arg.FilePath,
		arg.FileHash,
	)
	return err
}

const deleteTrack = `-- name: DeleteTrack :exec
DELETE FROM track
WHERE track.id = $1
`

func (q *Queries) DeleteTrack(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteTrack, id)
	return err
}

const getTrackArtists = `-- name: GetTrackArtists :many
SELECT track_id, artist_id, id, title FROM track_artist
JOIN artist ON artist.id = track_artist.artist_id
WHERE track_artist.track_id = $1
`

type GetTrackArtistsRow struct {
	TrackID  string
	ArtistID string
	ID       string
	Title    string
}

func (q *Queries) GetTrackArtists(ctx context.Context, trackID string) ([]GetTrackArtistsRow, error) {
	rows, err := q.db.Query(ctx, getTrackArtists, trackID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTrackArtistsRow
	for rows.Next() {
		var i GetTrackArtistsRow
		if err := rows.Scan(
			&i.TrackID,
			&i.ArtistID,
			&i.ID,
			&i.Title,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTrackByFilePath = `-- name: GetTrackByFilePath :one
SELECT id, title, album_id, disc_number, track_number, year, genre, composer, file_path, file_hash FROM track
WHERE track.file_path = $1
LIMIT 1
`

func (q *Queries) GetTrackByFilePath(ctx context.Context, filePath string) (Track, error) {
	row := q.db.QueryRow(ctx, getTrackByFilePath, filePath)
	var i Track
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.AlbumID,
		&i.DiscNumber,
		&i.TrackNumber,
		&i.Year,
		&i.Genre,
		&i.Composer,
		&i.FilePath,
		&i.FileHash,
	)
	return i, err
}

const getTrackByHash = `-- name: GetTrackByHash :one
SELECT id, title, album_id, disc_number, track_number, year, genre, composer, file_path, file_hash FROM track
WHERE track.id = $1
LIMIT 1
`

func (q *Queries) GetTrackByHash(ctx context.Context, id string) (Track, error) {
	row := q.db.QueryRow(ctx, getTrackByHash, id)
	var i Track
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.AlbumID,
		&i.DiscNumber,
		&i.TrackNumber,
		&i.Year,
		&i.Genre,
		&i.Composer,
		&i.FilePath,
		&i.FileHash,
	)
	return i, err
}

const getTracks = `-- name: GetTracks :many
SELECT id, title, album_id, disc_number, track_number, year, genre, composer, file_path, file_hash FROM track
`

func (q *Queries) GetTracks(ctx context.Context) ([]Track, error) {
	rows, err := q.db.Query(ctx, getTracks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Track
	for rows.Next() {
		var i Track
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.AlbumID,
			&i.DiscNumber,
			&i.TrackNumber,
			&i.Year,
			&i.Genre,
			&i.Composer,
			&i.FilePath,
			&i.FileHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markTrackArtist = `-- name: MarkTrackArtist :exec
INSERT INTO track_artist (track_id, artist_id)
VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type MarkTrackArtistParams struct {
	TrackID  string
	ArtistID string
}

func (q *Queries) MarkTrackArtist(ctx context.Context, arg MarkTrackArtistParams) error {
	_, err := q.db.Exec(ctx, markTrackArtist, arg.TrackID, arg.ArtistID)
	return err
}
