// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: user.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO app_user (id, username, created_at, password_enc, password_hash, last_login)
VALUES ($1, $2, $3, $4, $5, now())
`

type CreateUserParams struct {
	ID           string
	Username     string
	CreatedAt    pgtype.Timestamptz
	PasswordEnc  []byte
	PasswordHash string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser,
		arg.ID,
		arg.Username,
		arg.CreatedAt,
		arg.PasswordEnc,
		arg.PasswordHash,
	)
	return err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, created_at, last_login, password_enc, password_hash FROM app_user
WHERE app_user.id = $1
LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (AppUser, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i AppUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.CreatedAt,
		&i.LastLogin,
		&i.PasswordEnc,
		&i.PasswordHash,
	)
	return i, err
}

const getUserByName = `-- name: GetUserByName :one
SELECT id, username, created_at, last_login, password_enc, password_hash FROM app_user
WHERE app_user.username = $1
LIMIT 1
`

func (q *Queries) GetUserByName(ctx context.Context, username string) (AppUser, error) {
	row := q.db.QueryRow(ctx, getUserByName, username)
	var i AppUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.CreatedAt,
		&i.LastLogin,
		&i.PasswordEnc,
		&i.PasswordHash,
	)
	return i, err
}

const updateUserEncPassword = `-- name: UpdateUserEncPassword :exec
UPDATE app_user
SET password_enc = $2,
    last_login = now()
WHERE app_user.id = $1
`

type UpdateUserEncPasswordParams struct {
	ID          string
	PasswordEnc []byte
}

func (q *Queries) UpdateUserEncPassword(ctx context.Context, arg UpdateUserEncPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserEncPassword, arg.ID, arg.PasswordEnc)
	return err
}
