// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: album.sql

package query

import (
	"context"
)

const createAlbum = `-- name: CreateAlbum :exec
INSERT INTO album (hash, name, total_tracks, total_discs)
VALUES ($1, $2, $3, $4)
ON CONFLICT (hash) DO UPDATE SET
    name = EXCLUDED.name,
    total_tracks = EXCLUDED.total_tracks,
    total_discs = EXCLUDED.total_discs
`

type CreateAlbumParams struct {
	Hash        string
	Name        string
	TotalTracks int32
	TotalDiscs  int32
}

func (q *Queries) CreateAlbum(ctx context.Context, arg CreateAlbumParams) error {
	_, err := q.db.Exec(ctx, createAlbum,
		arg.Hash,
		arg.Name,
		arg.TotalTracks,
		arg.TotalDiscs,
	)
	return err
}

const deleteAlbum = `-- name: DeleteAlbum :exec
DELETE FROM album WHERE album.hash = $1
`

func (q *Queries) DeleteAlbum(ctx context.Context, hash string) error {
	_, err := q.db.Exec(ctx, deleteAlbum, hash)
	return err
}

const getAlbumByHash = `-- name: GetAlbumByHash :one
SELECT hash, name, total_tracks, total_discs FROM album
WHERE album.hash = $1
LIMIT 1
`

func (q *Queries) GetAlbumByHash(ctx context.Context, hash string) (Album, error) {
	row := q.db.QueryRow(ctx, getAlbumByHash, hash)
	var i Album
	err := row.Scan(
		&i.Hash,
		&i.Name,
		&i.TotalTracks,
		&i.TotalDiscs,
	)
	return i, err
}

const getArtistAlbums = `-- name: GetArtistAlbums :many
SELECT album_hash, artist_hash, hash, name, total_tracks, total_discs FROM album_artist
JOIN album ON album.hash = album_artist.album_hash
WHERE album_artist.artist_hash = $1
`

type GetArtistAlbumsRow struct {
	AlbumHash   string
	ArtistHash  string
	Hash        string
	Name        string
	TotalTracks int32
	TotalDiscs  int32
}

func (q *Queries) GetArtistAlbums(ctx context.Context, artistHash string) ([]GetArtistAlbumsRow, error) {
	rows, err := q.db.Query(ctx, getArtistAlbums, artistHash)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetArtistAlbumsRow
	for rows.Next() {
		var i GetArtistAlbumsRow
		if err := rows.Scan(
			&i.AlbumHash,
			&i.ArtistHash,
			&i.Hash,
			&i.Name,
			&i.TotalTracks,
			&i.TotalDiscs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPaginatedAlbums = `-- name: GetPaginatedAlbums :many
SELECT hash, name, total_tracks, total_discs FROM album
LIMIT $1 OFFSET $2
`

type GetPaginatedAlbumsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) GetPaginatedAlbums(ctx context.Context, arg GetPaginatedAlbumsParams) ([]Album, error) {
	rows, err := q.db.Query(ctx, getPaginatedAlbums, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Album
	for rows.Next() {
		var i Album
		if err := rows.Scan(
			&i.Hash,
			&i.Name,
			&i.TotalTracks,
			&i.TotalDiscs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
