// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: artist.sql

package query

import (
	"context"
)

const createArtist = `-- name: CreateArtist :exec
INSERT INTO artist (hash, name)
VALUES ($1, $2)
ON CONFLICT (hash) DO UPDATE SET
    name = EXCLUDED.name
`

type CreateArtistParams struct {
	Hash string
	Name string
}

func (q *Queries) CreateArtist(ctx context.Context, arg CreateArtistParams) error {
	_, err := q.db.Exec(ctx, createArtist, arg.Hash, arg.Name)
	return err
}

const deleteArtist = `-- name: DeleteArtist :exec
DELETE FROM artist
WHERE artist.hash = $1
`

func (q *Queries) DeleteArtist(ctx context.Context, hash string) error {
	_, err := q.db.Exec(ctx, deleteArtist, hash)
	return err
}

const getAlbumArtists = `-- name: GetAlbumArtists :many
SELECT artist.hash, artist.name FROM album_artist
JOIN artist ON artist.hash = album_artist.artist_hash
WHERE album_artist.album_hash = $1
`

func (q *Queries) GetAlbumArtists(ctx context.Context, albumHash string) ([]Artist, error) {
	rows, err := q.db.Query(ctx, getAlbumArtists, albumHash)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Artist
	for rows.Next() {
		var i Artist
		if err := rows.Scan(&i.Hash, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTrackArtists = `-- name: GetTrackArtists :many
SELECT artist.hash, artist.name FROM track_artist
JOIN artist ON artist.hash = track_artist.artist_hash
WHERE track_artist.track_hash = $1
`

func (q *Queries) GetTrackArtists(ctx context.Context, trackHash string) ([]Artist, error) {
	rows, err := q.db.Query(ctx, getTrackArtists, trackHash)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Artist
	for rows.Next() {
		var i Artist
		if err := rows.Scan(&i.Hash, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAlbumArtist = `-- name: MarkAlbumArtist :exec
INSERT INTO album_artist (album_hash, artist_hash)
VALUES ($1, $2)
ON CONFLICT (album_hash, artist_hash) DO NOTHING
`

type MarkAlbumArtistParams struct {
	AlbumHash  string
	ArtistHash string
}

func (q *Queries) MarkAlbumArtist(ctx context.Context, arg MarkAlbumArtistParams) error {
	_, err := q.db.Exec(ctx, markAlbumArtist, arg.AlbumHash, arg.ArtistHash)
	return err
}

const markTrackArtist = `-- name: MarkTrackArtist :exec
INSERT INTO track_artist (track_hash, artist_hash)
VALUES ($1, $2)
ON CONFLICT (track_hash, artist_hash) DO NOTHING
`

type MarkTrackArtistParams struct {
	TrackHash  string
	ArtistHash string
}

func (q *Queries) MarkTrackArtist(ctx context.Context, arg MarkTrackArtistParams) error {
	_, err := q.db.Exec(ctx, markTrackArtist, arg.TrackHash, arg.ArtistHash)
	return err
}
