// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package query

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Album struct {
	Hash        string
	Name        string
	TotalTracks int32
	TotalDiscs  int32
}

type AlbumArtist struct {
	AlbumHash  string
	ArtistHash string
}

type AppUser struct {
	ID        string
	Username  string
	Password  string
	CreatedAt pgtype.Timestamptz
	LastLogin pgtype.Timestamptz
}

type Artist struct {
	Hash string
	Name string
}

type Track struct {
	Hash        string
	Name        string
	AlbumHash   pgtype.Text
	DiscNumber  int32
	TrackNumber int32
	Year        int32
	Genre       string
	FilePath    string
	FileHash    string
}

type TrackArtist struct {
	TrackHash  string
	ArtistHash string
}
