// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: track.sql

package query

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTrack = `-- name: CreateTrack :exec
INSERT INTO track (
    hash,
    name,
    album_hash,
    disc_number,
    track_number,
    year,
    genre,
    file_path,
    file_hash
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (hash) DO UPDATE SET
    name = EXCLUDED.name,
    album_hash = EXCLUDED.album_hash,
    disc_number = EXCLUDED.disc_number,
    track_number = EXCLUDED.track_number,
    year = EXCLUDED.year,
    genre = EXCLUDED.genre,
    file_path = EXCLUDED.file_path,
    file_hash = EXCLUDED.file_hash
`

type CreateTrackParams struct {
	Hash        string
	Name        string
	AlbumHash   pgtype.Text
	DiscNumber  int32
	TrackNumber int32
	Year        int32
	Genre       string
	FilePath    string
	FileHash    string
}

func (q *Queries) CreateTrack(ctx context.Context, arg CreateTrackParams) error {
	_, err := q.db.Exec(ctx, createTrack,
		arg.Hash,
		arg.Name,
		arg.AlbumHash,
		arg.DiscNumber,
		arg.TrackNumber,
		arg.Year,
		arg.Genre,
		arg.FilePath,
		arg.FileHash,
	)
	return err
}

const deleteTrack = `-- name: DeleteTrack :exec
DELETE FROM track WHERE track.hash = $1
`

func (q *Queries) DeleteTrack(ctx context.Context, hash string) error {
	_, err := q.db.Exec(ctx, deleteTrack, hash)
	return err
}

const getAlbumTracks = `-- name: GetAlbumTracks :many
SELECT hash, name, album_hash, disc_number, track_number, year, genre, file_path, file_hash FROM track
WHERE track.album_hash = $1
ORDER BY disc_number, track_number
`

func (q *Queries) GetAlbumTracks(ctx context.Context, albumHash pgtype.Text) ([]Track, error) {
	rows, err := q.db.Query(ctx, getAlbumTracks, albumHash)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Track
	for rows.Next() {
		var i Track
		if err := rows.Scan(
			&i.Hash,
			&i.Name,
			&i.AlbumHash,
			&i.DiscNumber,
			&i.TrackNumber,
			&i.Year,
			&i.Genre,
			&i.FilePath,
			&i.FileHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getArtistTracks = `-- name: GetArtistTracks :many
SELECT track.hash, track.name, track.album_hash, track.disc_number, track.track_number, track.year, track.genre, track.file_path, track.file_hash FROM track_artist
JOIN track ON track.hash = track_artist.track_hash
WHERE track_artist.artist_hash = $1
`

func (q *Queries) GetArtistTracks(ctx context.Context, artistHash string) ([]Track, error) {
	rows, err := q.db.Query(ctx, getArtistTracks, artistHash)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Track
	for rows.Next() {
		var i Track
		if err := rows.Scan(
			&i.Hash,
			&i.Name,
			&i.AlbumHash,
			&i.DiscNumber,
			&i.TrackNumber,
			&i.Year,
			&i.Genre,
			&i.FilePath,
			&i.FileHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPaginatedTracks = `-- name: GetPaginatedTracks :many
SELECT hash, name, album_hash, disc_number, track_number, year, genre, file_path, file_hash FROM track
LIMIT $1 OFFSET $2
`

type GetPaginatedTracksParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) GetPaginatedTracks(ctx context.Context, arg GetPaginatedTracksParams) ([]Track, error) {
	rows, err := q.db.Query(ctx, getPaginatedTracks, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Track
	for rows.Next() {
		var i Track
		if err := rows.Scan(
			&i.Hash,
			&i.Name,
			&i.AlbumHash,
			&i.DiscNumber,
			&i.TrackNumber,
			&i.Year,
			&i.Genre,
			&i.FilePath,
			&i.FileHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTrackByHash = `-- name: GetTrackByHash :one
SELECT hash, name, album_hash, disc_number, track_number, year, genre, file_path, file_hash FROM track
WHERE track.hash = $1
LIMIT 1
`

func (q *Queries) GetTrackByHash(ctx context.Context, hash string) (Track, error) {
	row := q.db.QueryRow(ctx, getTrackByHash, hash)
	var i Track
	err := row.Scan(
		&i.Hash,
		&i.Name,
		&i.AlbumHash,
		&i.DiscNumber,
		&i.TrackNumber,
		&i.Year,
		&i.Genre,
		&i.FilePath,
		&i.FileHash,
	)
	return i, err
}

const getTrackHashes = `-- name: GetTrackHashes :many
SELECT hash, file_hash FROM track
`

type GetTrackHashesRow struct {
	Hash     string
	FileHash string
}

func (q *Queries) GetTrackHashes(ctx context.Context) ([]GetTrackHashesRow, error) {
	rows, err := q.db.Query(ctx, getTrackHashes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTrackHashesRow
	for rows.Next() {
		var i GetTrackHashesRow
		if err := rows.Scan(&i.Hash, &i.FileHash); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
