// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: user.sql

package query

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO app_user (id, username, password, created_at, last_login)
VALUES ($1, $2, $3, $4, $5)
`

type CreateUserParams struct {
	ID        string
	Username  string
	Password  string
	CreatedAt pgtype.Timestamptz
	LastLogin pgtype.Timestamptz
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser,
		arg.ID,
		arg.Username,
		arg.Password,
		arg.CreatedAt,
		arg.LastLogin,
	)
	return err
}

const deleteUserByID = `-- name: DeleteUserByID :exec
DELETE FROM app_user
WHERE app_user.id = $1
`

func (q *Queries) DeleteUserByID(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteUserByID, id)
	return err
}

const getUserByID = `-- name: GetUserByID :one
SELECT
    app_user.id,
    app_user.username,
    app_user.created_at,
    app_user.last_login
FROM app_user
WHERE app_user.id = $1
LIMIT 1
`

type GetUserByIDRow struct {
	ID        string
	Username  string
	CreatedAt pgtype.Timestamptz
	LastLogin pgtype.Timestamptz
}

func (q *Queries) GetUserByID(ctx context.Context, id string) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.CreatedAt,
		&i.LastLogin,
	)
	return i, err
}

const getUserLogin = `-- name: GetUserLogin :one
SELECT
    app_user.id,
    app_user.username,
    app_user.created_at,
    app_user.last_login
FROM app_user
WHERE
    app_user.username = $1 AND app_user.password = $2
LIMIT 1
`

type GetUserLoginParams struct {
	Username string
	Password string
}

type GetUserLoginRow struct {
	ID        string
	Username  string
	CreatedAt pgtype.Timestamptz
	LastLogin pgtype.Timestamptz
}

// for legacy subsonic requests with plaintext passwords (ew)
func (q *Queries) GetUserLogin(ctx context.Context, arg GetUserLoginParams) (GetUserLoginRow, error) {
	row := q.db.QueryRow(ctx, getUserLogin, arg.Username, arg.Password)
	var i GetUserLoginRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.CreatedAt,
		&i.LastLogin,
	)
	return i, err
}

const getUserLoginByHash = `-- name: GetUserLoginByHash :one
SELECT
    app_user.id,
    app_user.username,
    app_user.created_at,
    app_user.last_login
FROM app_user
WHERE
    app_user.username = $1 AND md5(app_user.password || $3) = $2
LIMIT 1
`

type GetUserLoginByHashParams struct {
	Username   string
	Password   string
	Password_2 string
}

type GetUserLoginByHashRow struct {
	ID        string
	Username  string
	CreatedAt pgtype.Timestamptz
	LastLogin pgtype.Timestamptz
}

func (q *Queries) GetUserLoginByHash(ctx context.Context, arg GetUserLoginByHashParams) (GetUserLoginByHashRow, error) {
	row := q.db.QueryRow(ctx, getUserLoginByHash, arg.Username, arg.Password, arg.Password_2)
	var i GetUserLoginByHashRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.CreatedAt,
		&i.LastLogin,
	)
	return i, err
}

const markUserLogin = `-- name: MarkUserLogin :exec
UPDATE app_user
SET last_login = now()
WHERE app_user.id = $1
`

func (q *Queries) MarkUserLogin(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, markUserLogin, id)
	return err
}
