version: "3"

dotenv: [".env"]

tasks:
  default:
    cmds:
      - sqlc generate

  up:
    cmds:
      - goose -dir "schema/migrations" postgres $DATABASE_URL up

  reset:
    cmds:
      - task: default
      - docker compose down
      - docker compose up -d
      - sleep 3
      - task: up
