version: "3"

dotenv: [".env"]

tasks:
  up:
    cmds:
      - goose postgres $DATABASE_URL -dir schema/migrations up

  reset:
    cmds:
      - docker compose down && docker compose up -d
      - sleep 3
      - task: up
      - task: default

  default:
    cmds:
      - sqlc generate
